//! Plaintext, ciphertext, and submitted ballot types for ElectionGuard v2.1.
//!
//! Domain model:
//! ```text
//! PlaintextBallot          — voter intent (human-readable)
//!   └── PlaintextBallotContest
//!         └── PlaintextBallotSelection
//!
//! CiphertextBallot         — encrypted ballot (all nonces present)
//!   └── CiphertextBallotContest
//!         └── CiphertextBallotSelection
//!
//! SubmittedBallot          — nonces stripped, state Cast | Spoiled | Challenged
//! ```

use crate::elgamal::{ElGamalCiphertext, HashedElGamalCiphertext};
use crate::election::CiphertextElectionContext;
use crate::error::{Error, Result};
use crate::group::{ElementModP, ElementModQ};
use crate::hash::{hash_elems_v21, CryptoHashable, HashableValue};
use crate::proof::ranged::RangedChaumPedersenProof;
use serde::{Deserialize, Serialize};

// ── Domain separator constants for ballot hashing ─────────────────────────
use crate::group::constants::{EG_DS_CONFIRMATION_CODE, EG_DS_CONTEST_HASH};

// ── BallotBoxState ─────────────────────────────────────────────────────────

/// The state of a ballot in the ballot box.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum BallotBoxState {
    #[default]
    Unknown,
    Cast,
    Spoiled,
    Challenged,
}

// ── Plaintext types ────────────────────────────────────────────────────────

/// A single selection in a plaintext ballot.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PlaintextBallotSelection {
    pub object_id: String,
    /// 0 = not voted, 1 = voted (or a cumulative count ≤ max votes).
    pub vote: u64,
    /// `true` if this is a placeholder selection (auto-generated by the system).
    #[serde(default)]
    pub is_placeholder_selection: bool,
    /// Optional write-in text or other extended data.
    pub extended_data: Option<String>,
}

/// A single contest in a plaintext ballot.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PlaintextBallotContest {
    pub object_id: String,
    pub selections: Vec<PlaintextBallotSelection>,
}

impl PlaintextBallotContest {
    /// Returns `true` if this contest satisfies the manifest constraints.
    ///
    /// Rules:
    /// 1. Object ID matches.
    /// 2. Exactly `expected_num_selections` selections present.
    /// 3. Total votes ≤ `votes_allowed` (defaults to `expected_num_elected`).
    /// 4. Each vote is 0 or 1 (for `OneOfM` and `NOfM` style contests).
    pub fn is_valid(
        &self,
        expected_object_id: &str,
        expected_num_selections: u64,
        expected_num_elected: u64,
        votes_allowed: Option<u64>,
    ) -> bool {
        if self.object_id != expected_object_id {
            return false;
        }
        if self.selections.len() as u64 != expected_num_selections {
            return false;
        }
        let max_votes = votes_allowed.unwrap_or(expected_num_elected);
        let total_votes: u64 = self.selections.iter().map(|s| s.vote).sum();
        if total_votes > max_votes {
            return false;
        }
        // Overvote check: total across non-placeholder selections must not exceed limit.
        let real_votes: u64 = self
            .selections
            .iter()
            .filter(|s| !s.is_placeholder_selection)
            .map(|s| s.vote)
            .sum();
        if real_votes > max_votes {
            return false;
        }
        true
    }
}

/// A complete plaintext ballot representing voter intent.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PlaintextBallot {
    /// Unique ballot object ID (e.g. a UUID or sequential number).
    pub object_id: String,
    /// The ballot style ID from the manifest.
    pub style_id: String,
    pub contests: Vec<PlaintextBallotContest>,
}

impl PlaintextBallot {
    /// Deserialize from a JSON string.
    pub fn from_json(json: &str) -> Result<Self> {
        serde_json::from_str(json)
            .map_err(|e| Error::Serialization(format!("PlaintextBallot::from_json: {}", e)))
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String> {
        serde_json::to_string(self)
            .map_err(|e| Error::Serialization(format!("PlaintextBallot::to_json: {}", e)))
    }
}

// ── Ciphertext types ───────────────────────────────────────────────────────

/// An encrypted ballot selection.
///
/// Corresponds to a single `SelectionDescription` in the manifest.
/// Contains both the encrypted vote (`ciphertext`) and a range proof
/// that proves the vote is in `[0, range_limit]`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CiphertextBallotSelection {
    pub object_id: String,
    pub sequence_order: u64,
    /// Hash of the `SelectionDescription` from the manifest.
    pub description_hash: ElementModQ,
    /// The ElGamal encrypted vote.
    pub ciphertext: ElGamalCiphertext,
    /// `true` if this is a placeholder selection.
    #[serde(default)]
    pub is_placeholder: bool,
    /// The encryption nonce (present until `clear_nonce()` is called).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nonce: Option<ElementModQ>,
    /// Crypto hash of this selection (binds object_id, description_hash, ciphertext).
    pub crypto_hash: ElementModQ,
    /// Zero-knowledge range proof that vote ∈ [0, range_limit].
    pub proof: RangedChaumPedersenProof,
    /// Optional hashed ElGamal ciphertext for extended data (e.g. write-in text).
    pub extended_data: Option<ElGamalCiphertext>,
}

impl CiphertextBallotSelection {
    /// Construct a `CiphertextBallotSelection` from pre-computed parts.
    ///
    /// The `crypto_hash` is computed automatically from the other fields.
    ///
    /// Note: full proof generation is deferred to Phase 4 encryption.
    /// This constructor accepts a pre-built proof for use in tests and
    /// the encryption pipeline.
    #[allow(clippy::too_many_arguments)]
    pub fn make(
        object_id: &str,
        sequence_order: u64,
        description_hash: &ElementModQ,
        ciphertext: ElGamalCiphertext,
        _context: &CiphertextElectionContext,
        _plaintext: u64,
        nonce: &ElementModQ,
        is_placeholder: bool,
        proof: RangedChaumPedersenProof,
    ) -> Result<Self> {
        let mut sel = Self {
            object_id: object_id.to_string(),
            sequence_order,
            description_hash: description_hash.clone(),
            ciphertext,
            is_placeholder,
            nonce: Some(nonce.clone()),
            crypto_hash: ElementModQ::zero().clone(),
            proof,
            extended_data: None,
        };
        // Compute and store the selection hash.
        sel.crypto_hash = sel.crypto_hash()?;
        Ok(sel)
    }

    /// Check validity of the selection encryption.
    ///
    /// For Phase 3: verifies the range proof using the public key and extended hash.
    /// (Phase 4 will implement real proof verification.)
    pub fn is_valid_encryption(
        &self,
        _encryption_seed: &ElementModQ,
        _public_key: &ElementModP,
        _extended_hash: &ElementModQ,
    ) -> bool {
        // Phase 4 will implement real proof verification.
        // For now we just check that the stored crypto_hash matches what we'd compute.
        if let Ok(expected) = self.crypto_hash() {
            expected == self.crypto_hash
        } else {
            false
        }
    }

    /// Remove the encryption nonce (call after the ballot is submitted).
    pub fn clear_nonce(&mut self) {
        self.nonce = None;
    }
}

impl CryptoHashable for CiphertextBallotSelection {
    /// Compute `H(object_id, description_hash, pad, data)`.
    fn crypto_hash(&self) -> Result<ElementModQ> {
        // Use the extended_base_hash as the HMAC key.
        // For selection hashes we use a well-known 0x20 domain separator
        // (EG_DS_SELECTION_ENC_ID) but here we hash the *commitment* of a
        // selection (pad and data of ciphertext).  Use 0x21 (EG_DS_ENCRYPTION_NONCE).
        use crate::group::constants::EG_DS_ENCRYPTION_NONCE;
        // We don't have the extended_hash here; use description_hash as the key.
        hash_elems_v21(
            &self.description_hash,
            EG_DS_ENCRYPTION_NONCE,
            &[
                HashableValue::Str(&self.object_id),
                HashableValue::ModQ(&self.description_hash),
                HashableValue::ModP(&self.ciphertext.pad),
                HashableValue::ModP(&self.ciphertext.data),
            ],
        )
    }
}

/// An encrypted contest (accumulation of encrypted selections).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CiphertextBallotContest {
    pub object_id: String,
    pub sequence_order: u64,
    /// Hash of the `ContestDescription` from the manifest.
    pub description_hash: ElementModQ,
    pub selections: Vec<CiphertextBallotSelection>,
    /// The contest encryption nonce (present until `clear_nonces()` is called).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nonce: Option<ElementModQ>,
    /// Homomorphic accumulation of all selection ciphertexts.
    pub ciphertext_accumulation: ElGamalCiphertext,
    /// Crypto hash of this contest.
    pub crypto_hash: ElementModQ,
    /// Range proof that the total vote count equals `number_elected`.
    pub proof: RangedChaumPedersenProof,
    /// Optional hashed ElGamal ciphertext for contest data.
    pub hashed_elgamal: Option<HashedElGamalCiphertext>,
}

impl CiphertextBallotContest {
    /// Construct a `CiphertextBallotContest` from pre-computed parts.
    #[allow(clippy::too_many_arguments)]
    pub fn make(
        object_id: &str,
        sequence_order: u64,
        description_hash: &ElementModQ,
        selections: Vec<CiphertextBallotSelection>,
        _context: &CiphertextElectionContext,
        _number_selected: u64,
        _number_elected: u64,
        nonce: Option<&ElementModQ>,
        proof: RangedChaumPedersenProof,
        hashed_elgamal: Option<HashedElGamalCiphertext>,
    ) -> Result<Self> {
        let ciphertext_accumulation = {
            let refs: Vec<&ElGamalCiphertext> = selections.iter().map(|s| &s.ciphertext).collect();
            crate::elgamal::elgamal_accumulate(&refs)
        };

        let mut contest = Self {
            object_id: object_id.to_string(),
            sequence_order,
            description_hash: description_hash.clone(),
            selections,
            nonce: nonce.cloned(),
            ciphertext_accumulation,
            crypto_hash: ElementModQ::zero().clone(),
            proof,
            hashed_elgamal,
        };
        contest.crypto_hash = contest.crypto_hash()?;
        Ok(contest)
    }

    /// Aggregate all selection nonces by summing mod Q.
    pub fn aggregate_nonce(&self) -> Result<ElementModQ> {
        use crate::group::add_mod_q;
        let mut agg = ElementModQ::zero().clone();
        for sel in &self.selections {
            let n = sel.nonce.as_ref().ok_or_else(|| {
                Error::InvalidBallot("selection nonce has already been cleared".to_string())
            })?;
            agg = add_mod_q(&agg, n);
        }
        Ok(agg)
    }

    /// Homomorphic accumulation of all selection ciphertexts.
    pub fn elgamal_accumulate(&self) -> ElGamalCiphertext {
        let refs: Vec<&ElGamalCiphertext> = self.selections.iter().map(|s| &s.ciphertext).collect();
        crate::elgamal::elgamal_accumulate(&refs)
    }

    /// Check validity of the contest encryption (all selections valid).
    pub fn is_valid_encryption(
        &self,
        encryption_seed: &ElementModQ,
        public_key: &ElementModP,
        extended_hash: &ElementModQ,
    ) -> bool {
        if self.elgamal_accumulate() != self.ciphertext_accumulation {
            return false;
        }
        self.selections
            .iter()
            .all(|s| s.is_valid_encryption(encryption_seed, public_key, extended_hash))
    }

    /// Strip nonces from all selections and from this contest.
    pub fn clear_nonces(&mut self) {
        self.nonce = None;
        for sel in &mut self.selections {
            sel.clear_nonce();
        }
    }
}

impl CryptoHashable for CiphertextBallotContest {
    /// Compute the contest hash: `H(description_hash, accumulation_pad, accumulation_data, ...)`.
    fn crypto_hash(&self) -> Result<ElementModQ> {
        // Collect selection hashes.
        let sel_hashes: Result<Vec<ElementModQ>> =
            self.selections.iter().map(|s| s.crypto_hash()).collect();
        let sel_hashes = sel_hashes?;

        let mut args: Vec<HashableValue<'_>> = vec![
            HashableValue::Str(&self.object_id),
            HashableValue::ModQ(&self.description_hash),
            HashableValue::ModP(&self.ciphertext_accumulation.pad),
            HashableValue::ModP(&self.ciphertext_accumulation.data),
        ];
        for sh in &sel_hashes {
            args.push(HashableValue::ModQ(sh));
        }

        hash_elems_v21(&self.description_hash, EG_DS_CONTEST_HASH, &args)
    }
}

// ── CiphertextBallot ───────────────────────────────────────────────────────

/// A fully encrypted ballot (nonces still present).
///
/// After voter submission, nonces are stripped and state is set via
/// `cast()` or `spoil()` to produce a `SubmittedBallot`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CiphertextBallot {
    /// Unique ballot ID (typically a UUID string).
    pub object_id: String,
    /// The ballot style ID from the manifest.
    pub style_id: String,
    /// Hash of the election manifest.
    pub manifest_hash: ElementModQ,
    /// Seed used to derive the confirmation code chain.
    pub ballot_code_seed: ElementModQ,
    pub contests: Vec<CiphertextBallotContest>,
    /// Confirmation code = H(seed, timestamp, ballot_hash).
    pub ballot_code: ElementModQ,
    /// Unix timestamp at time of encryption.
    pub timestamp: u64,
    /// Master ballot nonce (present until nonces are stripped).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nonce: Option<ElementModQ>,
    /// Crypto hash of this ballot.
    pub crypto_hash: ElementModQ,
    pub state: BallotBoxState,
    // ── v2.1 fields ──
    /// v2.1 ballot ID (selection encryption ID seed).
    pub ballot_id: Option<ElementModQ>,
    /// Encrypted ballot nonce (for voter receipt).
    pub nonce_ciphertext: Option<HashedElGamalCiphertext>,
    /// Chaining field bytes (for confirmation code chaining).
    pub chaining_field: Option<Vec<u8>>,
    /// Selection encryption ID used for all selection proofs in this ballot.
    pub selection_encryption_id: Option<ElementModQ>,
}

impl CiphertextBallot {
    /// Construct a `CiphertextBallot` from pre-computed parts.
    #[allow(clippy::too_many_arguments)]
    pub fn make(
        object_id: &str,
        style_id: &str,
        manifest_hash: &ElementModQ,
        context: &CiphertextElectionContext,
        contests: Vec<CiphertextBallotContest>,
        nonce: Option<&ElementModQ>,
        timestamp: u64,
        ballot_code_seed: Option<&ElementModQ>,
    ) -> Result<Self> {
        let code_seed = ballot_code_seed
            .cloned()
            .unwrap_or_else(|| context.extended_base_hash.clone());

        // ballot_code = H(extended_hash; 0x29, code_seed, timestamp, ballot_hash_placeholder)
        // Use a placeholder ballot hash of all-zero for now; real ballot hash is set
        // after full construction.  The Phase 5 `ballot_code.rs` provides the canonical
        // implementation.
        let ballot_code = hash_elems_v21(
            &context.extended_base_hash,
            EG_DS_CONFIRMATION_CODE,
            &[
                HashableValue::ModQ(&code_seed),
                HashableValue::U64(timestamp),
            ],
        )?;

        let mut ballot = Self {
            object_id: object_id.to_string(),
            style_id: style_id.to_string(),
            manifest_hash: manifest_hash.clone(),
            ballot_code_seed: code_seed,
            contests,
            ballot_code,
            timestamp,
            nonce: nonce.cloned(),
            crypto_hash: ElementModQ::zero().clone(),
            state: BallotBoxState::Unknown,
            ballot_id: None,
            nonce_ciphertext: None,
            chaining_field: None,
            selection_encryption_id: None,
        };
        ballot.crypto_hash = ballot.crypto_hash()?;
        Ok(ballot)
    }

    /// Returns `true` if the ballot is correctly encrypted relative to the
    /// manifest and election context.
    pub fn is_valid_encryption(
        &self,
        manifest_hash: &ElementModQ,
        public_key: &ElementModP,
        extended_hash: &ElementModQ,
    ) -> bool {
        if self.manifest_hash != *manifest_hash {
            return false;
        }
        self.contests.iter().all(|c| {
            c.is_valid_encryption(&c.description_hash.clone(), public_key, extended_hash)
        })
    }

    /// Strip nonces and mark this ballot as **Cast**.
    pub fn cast(&mut self) {
        self.state = BallotBoxState::Cast;
        self.nonce = None;
        for c in &mut self.contests {
            c.clear_nonces();
        }
    }

    /// Strip nonces and mark this ballot as **Spoiled** (for audit/challenge).
    pub fn spoil(&mut self) {
        self.state = BallotBoxState::Spoiled;
        self.nonce = None;
        for c in &mut self.contests {
            c.clear_nonces();
        }
    }

    /// Deserialize from a JSON string.
    pub fn from_json(json: &str) -> Result<Self> {
        serde_json::from_str(json)
            .map_err(|e| Error::Serialization(format!("CiphertextBallot::from_json: {}", e)))
    }

    /// Serialize to a compact JSON string (nonces omitted due to `skip_serializing_if`).
    pub fn to_json(&self) -> Result<String> {
        serde_json::to_string(self)
            .map_err(|e| Error::Serialization(format!("CiphertextBallot::to_json: {}", e)))
    }

    /// Serialize to JSON, including nonces (for archival before submission).
    pub fn to_json_with_nonces(&self) -> Result<String> {
        // Nonces are already included in the struct (just not in the "public" JSON).
        // The `skip_serializing_if` annotation gates on `None`; since they are `Some`
        // before stripping, this method is equivalent to `to_json()` when nonces are present.
        self.to_json()
    }
}

impl CryptoHashable for CiphertextBallot {
    fn crypto_hash(&self) -> Result<ElementModQ> {
        let contest_hashes: Result<Vec<ElementModQ>> =
            self.contests.iter().map(|c| c.crypto_hash()).collect();
        let contest_hashes = contest_hashes?;

        let mut args: Vec<HashableValue<'_>> = vec![
            HashableValue::Str(&self.object_id),
            HashableValue::Str(&self.style_id),
            HashableValue::ModQ(&self.manifest_hash),
        ];
        for ch in &contest_hashes {
            args.push(HashableValue::ModQ(ch));
        }
        hash_elems_v21(&self.manifest_hash, EG_DS_CONFIRMATION_CODE, &args)
    }
}

// ── SubmittedBallot ────────────────────────────────────────────────────────

/// A ballot that has been submitted (nonces stripped, state Cast | Spoiled | Challenged).
///
/// Implements `Deref<Target = CiphertextBallot>` for read-only access to all ballot fields.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SubmittedBallot(pub CiphertextBallot);

impl SubmittedBallot {
    /// Create from a `CiphertextBallot`, stripping nonces and setting the given state.
    pub fn from_ciphertext(mut ballot: CiphertextBallot, state: BallotBoxState) -> Self {
        ballot.nonce = None;
        for c in &mut ballot.contests {
            c.clear_nonces();
        }
        ballot.state = state;
        Self(ballot)
    }

    /// Deserialize from a JSON string.
    pub fn from_json(json: &str) -> Result<Self> {
        serde_json::from_str(json)
            .map_err(|e| Error::Serialization(format!("SubmittedBallot::from_json: {}", e)))
    }

    /// Serialize to a JSON string.
    pub fn to_json(&self) -> Result<String> {
        serde_json::to_string(self)
            .map_err(|e| Error::Serialization(format!("SubmittedBallot::to_json: {}", e)))
    }
}

impl std::ops::Deref for SubmittedBallot {
    type Target = CiphertextBallot;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl std::ops::DerefMut for SubmittedBallot {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ballot_box_state_default() {
        let s = BallotBoxState::default();
        assert_eq!(s, BallotBoxState::Unknown);
    }

    #[test]
    fn ballot_box_state_serde() {
        let json = serde_json::to_string(&BallotBoxState::Cast).unwrap();
        assert_eq!(json, "\"cast\"");

        let back: BallotBoxState = serde_json::from_str("\"spoiled\"").unwrap();
        assert_eq!(back, BallotBoxState::Spoiled);

        let challenged: BallotBoxState = serde_json::from_str("\"challenged\"").unwrap();
        assert_eq!(challenged, BallotBoxState::Challenged);
    }

    #[test]
    fn plaintext_ballot_json_round_trip() {
        let ballot = PlaintextBallot {
            object_id: "ballot-1".to_string(),
            style_id: "style-1".to_string(),
            contests: vec![PlaintextBallotContest {
                object_id: "contest-1".to_string(),
                selections: vec![
                    PlaintextBallotSelection {
                        object_id: "sel-A".to_string(),
                        vote: 1,
                        is_placeholder_selection: false,
                        extended_data: None,
                    },
                    PlaintextBallotSelection {
                        object_id: "sel-B".to_string(),
                        vote: 0,
                        is_placeholder_selection: false,
                        extended_data: None,
                    },
                ],
            }],
        };

        let json = ballot.to_json().unwrap();
        let back = PlaintextBallot::from_json(&json).unwrap();
        assert_eq!(ballot.object_id, back.object_id);
        assert_eq!(ballot.style_id, back.style_id);
        assert_eq!(ballot.contests.len(), back.contests.len());
        assert_eq!(
            ballot.contests[0].selections[0].vote,
            back.contests[0].selections[0].vote
        );
    }

    #[test]
    fn plaintext_ballot_contest_is_valid() {
        let contest = PlaintextBallotContest {
            object_id: "contest-1".to_string(),
            selections: vec![
                PlaintextBallotSelection {
                    object_id: "sel-A".to_string(),
                    vote: 1,
                    is_placeholder_selection: false,
                    extended_data: None,
                },
                PlaintextBallotSelection {
                    object_id: "sel-B".to_string(),
                    vote: 0,
                    is_placeholder_selection: false,
                    extended_data: None,
                },
            ],
        };
        assert!(contest.is_valid("contest-1", 2, 1, Some(1)));
        // Wrong ID → invalid
        assert!(!contest.is_valid("contest-2", 2, 1, Some(1)));
        // Wrong selection count → invalid
        assert!(!contest.is_valid("contest-1", 3, 1, Some(1)));
        // Overvote → invalid
        let overvote = PlaintextBallotContest {
            object_id: "contest-1".to_string(),
            selections: vec![
                PlaintextBallotSelection {
                    object_id: "sel-A".to_string(),
                    vote: 1,
                    is_placeholder_selection: false,
                    extended_data: None,
                },
                PlaintextBallotSelection {
                    object_id: "sel-B".to_string(),
                    vote: 1,
                    is_placeholder_selection: false,
                    extended_data: None,
                },
            ],
        };
        assert!(!overvote.is_valid("contest-1", 2, 1, Some(1)));
    }

    #[test]
    fn submitted_ballot_strips_nonces() {
        use crate::elgamal::{elgamal_encrypt, ElGamalCiphertext};

        // Build a minimal ciphertext ballot with a fake nonce.
        let pk = ElementModP::g().clone();
        let nonce = ElementModQ::from_u64(42);
        let ct: ElGamalCiphertext = elgamal_encrypt(0, &nonce, &pk);

        // Build a stub proof (range_limit=0 so no individual proofs needed for existence check).
        let stub_proof = RangedChaumPedersenProof {
            range_limit: 0,
            individual_proofs: vec![],
            challenge: ElementModQ::from_u64(0),
        };

        let desc_hash = ElementModQ::from_u64(7);
        let sel = CiphertextBallotSelection {
            object_id: "sel-1".to_string(),
            sequence_order: 1,
            description_hash: desc_hash.clone(),
            ciphertext: ct.clone(),
            is_placeholder: false,
            nonce: Some(nonce.clone()),
            crypto_hash: ElementModQ::from_u64(0),
            proof: stub_proof.clone(),
            extended_data: None,
        };

        let contest_proof = RangedChaumPedersenProof {
            range_limit: 1,
            individual_proofs: vec![],
            challenge: ElementModQ::from_u64(0),
        };
        let contest = CiphertextBallotContest {
            object_id: "contest-1".to_string(),
            sequence_order: 1,
            description_hash: desc_hash.clone(),
            selections: vec![sel],
            nonce: Some(nonce.clone()),
            ciphertext_accumulation: ct.clone(),
            crypto_hash: ElementModQ::from_u64(0),
            proof: contest_proof,
            hashed_elgamal: None,
        };

        let manifest_hash = ElementModQ::from_u64(99);
        let ballot = CiphertextBallot {
            object_id: "ballot-1".to_string(),
            style_id: "style-1".to_string(),
            manifest_hash: manifest_hash.clone(),
            ballot_code_seed: ElementModQ::from_u64(1),
            contests: vec![contest],
            ballot_code: ElementModQ::from_u64(2),
            timestamp: 1_000_000,
            nonce: Some(nonce.clone()),
            crypto_hash: ElementModQ::from_u64(3),
            state: BallotBoxState::Unknown,
            ballot_id: None,
            nonce_ciphertext: None,
            chaining_field: None,
            selection_encryption_id: None,
        };

        let submitted = SubmittedBallot::from_ciphertext(ballot, BallotBoxState::Cast);
        assert_eq!(submitted.state, BallotBoxState::Cast);
        assert!(submitted.nonce.is_none(), "nonce must be stripped");
        assert!(
            submitted.contests[0].nonce.is_none(),
            "contest nonce must be stripped"
        );
        assert!(
            submitted.contests[0].selections[0].nonce.is_none(),
            "selection nonce must be stripped"
        );
    }

    #[test]
    fn submitted_ballot_spoil() {
        use crate::elgamal::elgamal_encrypt;

        let pk = ElementModP::g().clone();
        let nonce = ElementModQ::from_u64(5);
        let ct = elgamal_encrypt(0, &nonce, &pk);
        let stub_proof = RangedChaumPedersenProof {
            range_limit: 0,
            individual_proofs: vec![],
            challenge: ElementModQ::from_u64(0),
        };
        let ballot = CiphertextBallot {
            object_id: "ballot-2".to_string(),
            style_id: "style-1".to_string(),
            manifest_hash: ElementModQ::from_u64(1),
            ballot_code_seed: ElementModQ::from_u64(1),
            contests: vec![],
            ballot_code: ElementModQ::from_u64(2),
            timestamp: 0,
            nonce: Some(nonce),
            crypto_hash: ElementModQ::from_u64(0),
            state: BallotBoxState::Unknown,
            ballot_id: None,
            nonce_ciphertext: None,
            chaining_field: None,
            selection_encryption_id: None,
        };
        let _ = ct; // suppress unused warning
        let _ = stub_proof;
        let submitted = SubmittedBallot::from_ciphertext(ballot, BallotBoxState::Spoiled);
        assert_eq!(submitted.state, BallotBoxState::Spoiled);
        assert!(submitted.nonce.is_none());
    }

    #[test]
    fn ciphertext_ballot_cast_spoil_methods() {
        use crate::elgamal::elgamal_encrypt;

        let pk = ElementModP::g().clone();
        let nonce = ElementModQ::from_u64(5);
        let ct = elgamal_encrypt(0, &nonce, &pk);

        let mut ballot = CiphertextBallot {
            object_id: "b".to_string(),
            style_id: "s".to_string(),
            manifest_hash: ElementModQ::from_u64(1),
            ballot_code_seed: ElementModQ::from_u64(1),
            contests: vec![],
            ballot_code: ElementModQ::from_u64(2),
            timestamp: 0,
            nonce: Some(nonce.clone()),
            crypto_hash: ElementModQ::from_u64(0),
            state: BallotBoxState::Unknown,
            ballot_id: None,
            nonce_ciphertext: None,
            chaining_field: None,
            selection_encryption_id: None,
        };
        let _ = ct;

        ballot.cast();
        assert_eq!(ballot.state, BallotBoxState::Cast);
        assert!(ballot.nonce.is_none());

        // Reset for spoil test.
        ballot.nonce = Some(nonce);
        ballot.state = BallotBoxState::Unknown;
        ballot.spoil();
        assert_eq!(ballot.state, BallotBoxState::Spoiled);
        assert!(ballot.nonce.is_none());
    }
}
